config/routes.rb
Rails.application.routes.draw do
  resources :replies
  resources :users
  resources :contributions
  resources :authentications
  resources :replies
  resources :contributions
  resources :comments
  resources :users
  resources :asks
  resources :threads
  
  
    get '/auth/:provider/callback', to: 'sessions#create'
    
    root to: 'contributions#index'
    
    get 'delete_session', to: 'sessions#delete_session'
    
    get '/ask', to: 'contributions#ask'
    
    get '/thread/:id', to: 'contributions#thread'
    
    get "/users" => "users#index"
    
    get "/user/:id" => "users#show"
    
    get "/comments" => "comments#index"
    
    get "/contributions" => "contributions#index"
    
    get "/contribution/:id" => "contributions#show"
    
    get "/comments" => "comments#index"
    
    post "/user" => "users#create"
    
    post "/contributions/publish" => "contributions#create"
    
    post "/contribution/comment" => "comments#create"
    
    post "/contribution/comment/reply" => "replies#create"
    
    put "/contribution" => "contributions#upvote"
    
    put "/user/edit" => "users#update"
    
    put "/comment/delete"  => "comments#destroy"
    
    put "/contribution/edit" => "contributions#update"
    
    put "/contribution/delete" => "contributions#destroy"
    
    put "/reply/delete" => "replies#destroy"
    
    put "/contribution/upvote" => "contributions#upvote"
    
    put "/comment/upvote" => "comments#upvote"
    
    put "/reply/upvote" => "replies#upvote"
    
    put "/comment" => "comments#upvote"
    
    put "/reply" => "replies#upvote"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    include ActionView::Helpers::DateHelper
    belongs_to :user
    belongs_to :contribution
    has_many :replies
    acts_as_votable
    
    def getUserName
        if user 
          self.user.username
        else
          return "noUser"
        end
    end
    
    def getUserId
      if user
        self.user.id
      else
        return 1
      end
    end
    
    def getContribution
      return self.contribution
    end
    
    def hoursAgo
      distance_of_time_in_words_to_now(created_at)
    end
    
    def userName
      if user
          user.username
      else return "no te user"
      end
    end
  
    def userURL
      if user
          "https://enigmatic-citadel-88968.herokuapp.com/users/" + user_id.to_s
      else return "no te user"
      end
    end
    
    def numVotes
      self.get_upvotes.size
    end
    
    def numReplies
      self.replies.size
    end
    
    def getReplies
      @filtredRep = Array.new
    replies.reverse_each do |variable|
      @filtredRep.push(variable.as_json(methods: [:userName,:hoursAgo,:numVotes],
                                          except: [ :created_at]))
    end
    return @filtredRep
    end
      
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  # DONEEEEEEEEEEEEEEEE
  def index
    @comments = Comment.all
    @filtred = Array.new
    @comments.reverse_each do |variable|
      @filtred.push(variable.as_json(methods: [:userName,:hoursAgo,:numVotes,:getContribution],
                                          except: [:created_at]))
    end
    respond_to do |format|
      format.html {}
      format.json {
        authenticate
        render :json => @filtred
      }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end
  
  def upvote 
    if current_user 
      @comment= Comment.find(params[:id])
      @comment.upvote_by current_user
    else  
      information = request.raw_post
      data_parsed = JSON.parse information
      @comment = Comment.find(data_parsed["id"])
      @comment.upvote_by authenticate
    end
    
    respond_to do |format|
        format.js {render inline: "location.reload();" }
        format.json {
          authenticate
          render :json => @comment.as_json()
        }
    end 
  end  

  def downvote
    @comment = Comment.find(params[:id])
    @comment.downvote_by current_user
    redirect_to :back
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    
    respond_to do |format|
      format.html {
        if !session[:user_id]
          session[:contribution_id] = comment_params[:contribution_id]
          session[:comment] = true
          session[:body] = comment_params[:body]
          redirect_to "/auth/twitter" and return
        end
      }
      format.json{}
    end
    
    respond_to do |format|
      format.html {}
      format.json {
        if !Contribution.exists?(comment_params[:contribution_id])
            raise ActionController::ParameterMissing.new("There is no contribution with this id")
        end
      }
    end
    
    if session[:user_id] || authenticateCreation
      @comment = Comment.new(comment_params)
      if(session[:user_id])
        @comment.user= User.find(session[:user_id])
      end
      if(authenticateCreation) 
        @comment.user = session[:user_creation]
        information = request.raw_post
        data_parsed = JSON.parse(information)
        @comment.contribution_id = data_parsed["contribution_id"]
      end 
      
      respond_to do |format|
        if @comment.save
          format.html { redirect_to @comment.contribution, notice: 'Comment was successfully created.' }
          format.json { 
            render :json => @comment.as_json()
          }
        else
          format.html { render :new }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    end
  end 
  

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    respond_to do |format|
        format.html {}
        format.json { 
          if @comment.user != authenticate 
            raise ActionController::ParameterMissing.new("You cannot delete a comment that is not yours")
          end
        }
    end
      
      Reply.all.each do |reply|
        if reply.comment == @comment
          reply.destroy
        end
      end
    
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }
        format.json { head :no_content }
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      respond_to do |format|
        format.html { }
        format.json { raise ActionController::ParameterMissing.new("Format error: empty contribution_id") if params[:contribution_id].blank?
      raise ActionController::ParameterMissing.new("Format error: empty body") if params[:body].blank?}
      end
      
      params.require(:comment).permit( :contribution_id, :body, :user_id)
    end
    
    protected
    def authenticate
      authenticate_or_request_with_http_token do |token, options|
        User.find_by(auth_token: token)
      end
    end
    
    protected
    def authenticateCreation
      if session[:user_id]
        return false
      else
        authenticate_or_request_with_http_token do |token, options|
          session[:user_creation] = User.find_by(auth_token: token)
        end
      end
    end
    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

 <% session[:threads_id] = session[:user_id] %>
<div class="pageHeader">
 <b><%= link_to "Software 33 - Hacker News"  , contributions_path %> </b>   
    <%= link_to 'new', contributions_path %> | 
    <%= link_to 'comments',comments_path , {:style=>'color:white;', :class => "css_class"} %> | 
     <% if current_user %>
        <%= link_to 'threads', "/thread/" + String(current_user.id) %> | 
     <%end%>
    <%= link_to 'ask', "/ask" %> | 
    <%= link_to 'submit', new_contribution_path %> 
    <div class="user_session">
        <% if current_user %>
            Signed in as <%= link_to current_user.username, current_user %> |
            <%= link_to 'Logout', "/delete_session" %>  &nbsp;
            <div class=image2><img src= <%= current_user.profile_image %> alt="Profile Image" style="width:20px;height:20px;"></div>
        <% end %>
        <% if !current_user  %>
            <%= link_to "Sign in with Twitter", "/auth/twitter" %>
        <% end %>
    </div>
</div>

<ol class="pageCommentBody">
  <% @comments.each do |comment| %>
    <li class="list">
      <div class=subtitle>
        
        <td><%= 'Comment by user ' %><%= link_to comment.getUserName , comment.user %> </td> 
        <td><%= distance_of_time_in_words_to_now(comment.created_at) %></td>
        <td><%= ' ago ' %></td>
        <td>| points: <%= comment.get_upvotes.size%>  </td>
        <td>| on: <%= link_to comment.contribution.title, comment.contribution  %></td>
        <% if(current_user && !(current_user.liked? comment)) %>
          <td><b><%=link_to(image_tag('like.png'), {:controller => 'comments', :action => 'upvote', :id => comment.id}, {:method => :put, :remote => true}) %></b></td>
          <% end %> 
        <% if(current_user && (current_user.liked? comment)) %>
            <img src="http://www.clker.com/cliparts/P/S/9/I/l/S/234-ed-s-sd-hi.png" alt="Like Thumb" style="width:16px;height:16px;">
        <% end %>
          <% if(comment.getUserId == session[:user_id]) %>
            <td>| <b><%= link_to 'Destroy', comment, method: :delete %></b></td>
          <% end %>
      </div>
      <div>
        <td><%= comment.body %></td>
      </div>
    </li>
    <br>
  <% end %>
</ol> 
<br>