config/routes.rb
Rails.application.routes.draw do
  resources :replies
  resources :users
  resources :contributions
  resources :authentications
  resources :replies
  resources :contributions
  resources :comments
  resources :users
  resources :asks
  resources :threads
  
  
    get '/auth/:provider/callback', to: 'sessions#create'
    
    root to: 'contributions#index'
    
    get 'delete_session', to: 'sessions#delete_session'
    
    get '/ask', to: 'contributions#ask'
    
    get '/thread/:id', to: 'contributions#thread'
    
    get "/users" => "users#index"
    
    get "/user/:id" => "users#show"
    
    get "/comments" => "comments#index"
    
    get "/contributions" => "contributions#index"
    
    get "/contribution/:id" => "contributions#show"
    
    get "/comments" => "comments#index"
    
    post "/user" => "users#create"
    
    post "/contributions/publish" => "contributions#create"
    
    post "/contribution/comment" => "comments#create"
    
    post "/contribution/comment/reply" => "replies#create"
    
    put "/contribution" => "contributions#upvote"
    
    put "/user/edit" => "users#update"
    
    put "/comment/delete"  => "comments#destroy"
    
    put "/contribution/edit" => "contributions#update"
    
    put "/contribution/delete" => "contributions#destroy"
    
    put "/reply/delete" => "replies#destroy"
    
    put "/contribution/upvote" => "contributions#upvote"
    
    put "/comment/upvote" => "comments#upvote"
    
    put "/reply/upvote" => "replies#upvote"
    
    put "/comment" => "comments#upvote"
    
    put "/reply" => "replies#upvote"

end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  include ActionView::Helpers::DateHelper
  belongs_to :user
  has_many :comments
  before_save :default_values
  acts_as_votable
  def default_values
    self.user = User.find(user_id)
    self.puntuacio = 0
    self.created_at = DateTime.current
  end
  
  def getUserName
    if user
      user.username
    else return "no te user"
    end
  end
  
  def getUserId
    if user
      user_id
    else return "no te user"
    end
  end
  
  def numComments
    comments.count
  end
  
  def self.new_contribution(url,text)
    case type
    when 'url'
      Url_contribution.new
    when 'text'
      Ask_contribution.new
    end
  end
  
  def isAsk
    if text == "" || text == nil
      return false
    else return true
    end
  end
  
  def isURL
    if url == "" || url == nil
      return false
    else return true
    end
  end
  
  def findUrls
    Contribution.all 
  end
  
  def getToken
    user.token
  end
  
  def numVotes
    self.get_upvotes.size
  end
  
  def numComments
    comments.size
  end
  
  def userName
    if user
      user.username
    else return "no te user"
    end
  end
  
  def userURL
    if user
      "https://enigmatic-citadel-88968.herokuapp.com/users/" + user_id.to_s
    else return "no te user"
    end
  end
  
  def hoursAgo
    distance_of_time_in_words_to_now(created_at)
  end
  
  def showURL
    "https://enigmatic-citadel-88968.herokuapp.com/contributions/" + id.to_s
  end
  
  
  def getComments
    @filtred = Array.new
    comments.reverse_each do |variable|
      @filtred.push(variable.as_json(methods: [:userName,:hoursAgo,:numVotes,:getContribution,:getReplies],
                                          except: [:created_at]))
    end
    return @filtred
  end
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :set_contribution, only: [:show, :edit, :update, :destroy]


  helper_method :isLiked
  # GET /contributions
  # GET /contributions.json   
  # DONEEEEEEEEEEEEEEEE
  def index
    @contributions = Contribution.all
    @filtred = Array.new
    @contributions.reverse_each do |variable|
        if variable.isURL
          @filtred.push(variable.as_json(methods: [:numVotes, :userName, :userURL, :hoursAgo, :numComments, :showURL, :getComments], 
                                          except: [:text, :updated_at, :puntuacio, :created_at]) )
        end
    end
    respond_to do |format|
      format.html {}
     # format.json render :partial => "contributions/ask.json"
  
      format.json { #es como hacer un IF
        #authenticate
        render :json => @filtred
      }
    end
  end
  
  
  # GET /contributions/ask
  # GET /contributions/ask.json
  # DONEEEEEEEEEEEEEEEE
  def ask
    @contributions = Contribution.all
    @filtred = Array.new
    @contributions.reverse_each do |variable|
        if variable.isAsk
          @filtred.push(variable.as_json(methods: [:numVotes, :userName, :userURL, :hoursAgo, :numComments, :showURL,:getComments]) )
        end
    end
    respond_to do |format|
      format.html {}
     # format.json render :partial => "contributions/ask.json"
      
      format.json { #es como hacer un IF
        authenticate
        render :json => @filtred
      }
    end
  end
  
  # GET /thread/1
  # GET /thread.json
  # DONEEEEEEEEEEEEEEEE
  def thread
    @contributions = Contribution.all
    @filtred = Array.new
    @contributions.reverse_each do |variable|
        if variable.user == User.find(params[:id])
          if variable.isAsk
            @filtred.push(variable.as_json(methods: [:numVotes, :userName, :userURL, :hoursAgo, :numComments, :showURL], 
                                          except: [:url, :updated_at, :puntuacio, :created_at]) )
          end
          if variable.isURL
            @filtred.push(variable.as_json(methods: [:numVotes, :userName, :userURL, :hoursAgo, :numComments, :showURL], 
                                          except: [:text, :updated_at, :puntuacio, :created_at]) )
          end
        end
    end
    respond_to do |format|
      format.html {}
      format.json { #es como hacer un IF
        authenticate
        render :json => @filtred
      }
    end
  end

# GET /contributions/new
  def new
    @contribution = Contribution.new
  end

  # GET /contributions/1
  # GET /contributions/1.json
  # DONEEEEEEEEEEEEEEEE
  def show
    respond_to do |format|
      format.html {}
      format.json {
        authenticate
        #Escrivim la contribucio en funcio de si es ASK o URL
        if @contribution.isAsk                  #De la Contribution
          render :json => @contribution.as_json(methods: [:numVotes, :userName, :userURL, :hoursAgo, :numComments, :showURL], 
                                                except: [:url, :updated_at, :puntuacio, :user_id, :created_at],  
                                                          #De cada comment de la contribution
                                                include: { comments: {  #De cada reply del comentari
                                                          include: { replies: { 
                                                                    except: [:updated_at, :comment_id, :created_at],
                                                                    methods: [:numVotes, :userName, :userURL, :hoursAgo]} }, 
                                                          except: [:updated_at, :contribution_id, :created_at],
                                                          methods: [:numVotes, :userName, :userURL, :hoursAgo]} })
        end
        if @contribution.isURL                  #De la Contribution
          render :json => @contribution.as_json(methods: [:numVotes, :userName, :userURL, :hoursAgo, :numComments, :showURL], 
                                                except: [:text, :updated_at, :puntuacio, :user_id, :created_at, :id], 
                                                          #De cada comment de la contribution
                                                include: { comments: {  #De cada reply del comentari
                                                          include: { replies: { 
                                                                    except: [:updated_at, :comment_id, :user_id, :created_at],
                                                                    methods: [:numVotes, :userName, :userURL, :hoursAgo]} }, 
                                                          except: [:updated_at, :contribution_id, :created_at, :user_id],
                                                          methods: [:numVotes, :userName, :userURL, :hoursAgo]} })
        end
      }
    end
  end

 # PUT 
  def upvote 
    if current_user 
      @contribution= Contribution.find(params[:id])
      @contribution.upvote_by current_user
    end
    if !current_user 
      information = request.raw_post
      data_parsed = JSON.parse information
      @contribution = Contribution.find(data_parsed["id"])
      @contribution.upvote_by authenticate
    end
    respond_to do |format|
        format.js {render inline: "location.reload();" }
        format.json {
          authenticate
          #Escrivim la contribucio en funcio de si es ASK o URL
          if @contribution.isAsk                  #De la Contribution
            render :json => @contribution.as_json(methods: [:numVotes, :userURL, :userName, :showURL], 
                                                  except: [:url, :updated_at, :puntuacio, :user_id, :created_at])
          end
          if @contribution.isURL                  #De la Contribution
            render :json => @contribution.as_json(methods: [:numVotes, :userURL, :userName, :showURL], 
                                                  except: [:text, :updated_at, :puntuacio, :user_id, :created_at])
          end
      }
    end
  end  

  def downvote
    @contribution = Contribution.find(params[:id])
    @contribution.downvote_by current_user
    redirect_to :back
  end

  # GET /contributions/1/edit
  def edit
  end

  # POST /contributions
  # POST /contributions.json
  def create #-----> Hay q enviar siempre TITLE y los 2 parametros, pero dejando 1 vacio
    
    respond_to do |format|
      format.html {
        if !session[:user_id]
          session[:body] = contribution_params[:title]
          session[:url] = contribution_params[:url]
          session[:text] = contribution_params[:text]
          redirect_to "/auth/twitter" and return
        end
      }
      format.json{}
    end
    
    if (contribution_params[:url]!=nil && contribution_params[:url]!="" && contribution_params[:text] != nil && contribution_params[:text] !="")
      session[:body] = contribution_params[:title]
      session[:url] = contribution_params[:url]
      session[:text] = contribution_params[:text]
      respond_to do |format|
         format.html { redirect_to new_contribution_path, notice: "fill just url or text"}
         format.json { 
            raise ActionController::ParameterMissing.new("You cannot create a contribution with text and URL") 
         }
      end
    
    elsif (contribution_params[:text] == nil || contribution_params[:text]=="") && (contribution_params[:url] == nil || contribution_params[:url]=="")
      session[:body] = contribution_params[:title]
      respond_to do |format|
         format.html { redirect_to new_contribution_path, notice: "Fill text or url"}
         format.json {}
      end
      
    elsif contribution_params[:title] == nil || contribution_params[:title] == ""
      session[:url] = contribution_params[:url]
      session[:text] = contribution_params[:text]
      respond_to do |format|
         format.html { redirect_to new_contribution_path, notice: "Ha de tenir un titol"}
         format.json { raise ActionController::ParameterMissing.new("You cannot create a contribution without title") }
      end

    else 
      @contribution = Contribution.new(contribution_params)
      if(authenticateCreation) 
          @contribution.user = authenticateCreation  
      else
        @contribution.user = User.find(session[:user_id]) 
      end
      respond_to do |format|
        if @contribution.save
          format.html { redirect_to contributions_path, notice: 'Contribution was successfully created.' }
          format.json { render :show, status: :created, location: @contribution }
        else
          format.html { render :new }
          format.json { render json: @contribution.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  

  # PATCH/PUT /contributions/1
  # PATCH/PUT /contributions/1.json
  def update
    
    if @contribution.isAsk  
      if contribution_params[:url]
        respond_to do |format|
          format.html { redirect_to @contribution, notice: "This is an ask, can't be a URL" and return} 
          format.json { raise ActionController::ParameterMissing.new("You can't fill URL in a text contribution") }
        end
      end
    
    elsif @contribution.isURL  
      if contribution_params[:text] 
        respond_to do |format|
          format.html { redirect_to @contribution, notice: "This is an URL, can't be a text" and return} 
          format.json { 
            if contribution_params[:text] != ""
              raise ActionController::ParameterMissing.new("You can't fill text in a URL contribution") 
            end
          }
        end
      end
    end
      
    
    respond_to do |format|
        format.html {}
        format.json { 
          if @contribution.user != authenticate 
            raise ActionController::ParameterMissing.new("You cannot update a contribution that is not yours")
          end
        }
    end
    respond_to do |format|

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/views/contributions/_form.html.erb
<%= form_for(@contribution) do |f| %>
  <% if @contribution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contribution.errors.count, "error") %> prohibited this contribution from being saved:</h2>

      <ul>
      <% @contribution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <% if !(session[:body]) %>
      <%= f.text_field :title %>
    <% end %>
    <% if (session[:body]) %>
      <%= f.text_field :title, :value => session[:body] %>
      <% session.delete(:body) %>
    <% end %>
  </div>
  
  <div class="field">
    <%= f.label :url %><br>
    <% if !(session[:url]) %>
      <%= f.url_field :url %>
    <% end %>
    <% if (session[:url]) %>
     <%= f.text_field :url, :value => session[:url] %>
     <% session.delete(:url) %>
    <% end %>
  </div>
  
  
  
  <div class="field">
    <% if !(session[:url]) %>
      <%= f.label :or %><br><br>
      <%= f.label :text %><br>
      <% if !(session[:text]) %>
        <%= f.text_area :text %>
      <% end %>
      <% if (session[:text]) %>
        <%= f.text_area :text, :value => session[:text] %>
       <% session.delete(:text) %>
      <% end %>
    <% end %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  

<% end %>

app/views/contributions/ask.html.erb
<p id="notice"><%= notice %></p>

<div class="pageHeader">
 <b><%= link_to "Software 33 - Hacker News"  , contributions_path %> </b>   
    <%= link_to 'new', contributions_path %> | 
    <%= link_to 'comments',comments_path %> | 
     <% if current_user %>
        <%= link_to 'threads', "/thread/" + String(current_user.id) %> | 
     <%end%>
    <%= link_to 'ask', "/ask" , {:style=>'color:white;', :class => "css_class"} %> | 
    <%= link_to 'submit', new_contribution_path %> 
    <div class="user_session">
        <% if current_user %>
            Signed in as <%= link_to current_user.username, current_user %> |
            <%= link_to 'Logout', "/delete_session" %>  &nbsp;
            <div class=image2><img src= <%= current_user.profile_image %> alt="Profile Image" style="width:20px;height:20px;"></div>
        <% end %>
        <% if !current_user  %>
            <%= link_to "Sign in with Twitter", "/auth/twitter" %>
        <% end %>
    </div>
</div>

<ol class="pageBody">
  <% @contributions.reverse_each do |contribution| %>
    <% if contribution.isAsk %>
      <li class="list">
        <div class="ContributionTitle">
          <% if(current_user && !(current_user.liked? contribution)) %>
            <%=link_to(image_tag('like.png'),{:controller => 'contributions', :action => 'upvote', :id => contribution.id},{:method => :put, :remote => true} ) %>
          <% end %> 
          <% if(current_user && (current_user.liked? contribution)) %>
            <img src="http://www.clker.com/cliparts/P/S/9/I/l/S/234-ed-s-sd-hi.png" alt="Like Thumb" style="width:16px;height:16px;">
          <% end %>
          <%= link_to contribution.title, contribution %>
        </div>
        <div class="subtitle">
          <td><%= contribution.get_upvotes.size %> <%= ' points, by user ' %></td>
          <td><%= link_to contribution.getUserName , contribution.user %></td>
          <td><%= distance_of_time_in_words_to_now(contribution.created_at) %></td>
          <td><%= ' ago ' %></td>
          <td><%= '| ' %><%= link_to contribution.comments.count, contribution %> <%= link_to ' comments',contribution %></td>
        <!--<b><td><%= link_to 'Comments', contribution %></td></b>-->
          <% if(contribution.getUserId == session[:user_id]) %>
            <b><td><%= link_to 'Edit', edit_contribution_path(contribution) %></td></b>
            <b><td><%= link_to 'Destroy', contribution, method: :delete, data: { confirm: 'Are you sure?' } %></td></b>
          <% end %>
        </div>
      </li>
    <% end %>
  <% end %>
</ol> 

app/views/contributions/ask.json.erb
json.array!(@contributions) do |contribution|
  json.extract! contribution, :id, :title, :puntuacio, :url, :text, :user_id
  json.url contribution_url(contribution, format: :json)
end

app/views/contributions/edit.html.erb
<p/>
<div class="pageHeader">
 <b><%= link_to "Software 33 - Hacker News"  , contributions_path %></b> | 
 <font color="white"> Edit </font> 
    <div class="user_session">
        <% if current_user %>
            Signed in as <%= link_to current_user.username, current_user %> |
            <%= link_to 'Logout', "/delete_session" %>  &nbsp;
            <div class=image2><img src= <%= current_user.profile_image %> alt="Profile Image" style="width:20px;height:20px;"></div>
        <% end %>
        <% if !current_user  %>
            <%= link_to "Sign in with Twitter", "/auth/twitter" %>
        <% end %>
    </div>
</div>
<ol class=pageBody>
    <%= render 'form' %>
    <%= link_to 'Show', @contribution %>
</ol>

app/views/contributions/index.html.erb
<p id="notice"><%= notice %></p>

 <% session[:threads_id] = session[:user_id] %>
<div class="pageHeader">
    <b><%= link_to "Software 33 - Hacker News"  , contributions_path %> </b>   
    <%= link_to 'new', contributions_path , {:style=>'color:white;', :class => "css_class"} %> | 
    <%= link_to 'comments',comments_path %> | 
    <% if current_user %>
        <%= link_to 'threads', "/thread/" + String(current_user.id) %> | 
    <%end%>
    <%= link_to 'ask', "/ask" %> | 
    <%= link_to 'submit', new_contribution_path %>
    
    <div class="user_session">
        <% if current_user %>
            Signed in as <%= link_to current_user.username, current_user %> |
            <%= link_to 'Logout', "/delete_session" %>  &nbsp;
            <div class=image2><img src= <%= current_user.profile_image %> alt="Profile Image" style="width:20px;height:20px;"></div>
        <% end %>
        <% if !current_user  %>
            <%= link_to "Sign in with Twitter", "/auth/twitter" %>
        <% end %>
    </div>
</div>

<ol class="pageBody">
  <% @contributions.reverse_each do |contribution| %>
    <% if contribution.isURL %>
    <li class="list">
        <div class="ContributionTitle">
        <% if(current_user && !(current_user.liked? contribution)) %>
            <%=link_to(image_tag('like.png'),{:controller => 'contributions', :action => 'upvote', :id => contribution.id},{:method => :put, :remote => true} ) %>
        <% end %> 
        <% if(current_user && (current_user.liked? contribution)) %>
            <img src="http://www.clker.com/cliparts/P/S/9/I/l/S/234-ed-s-sd-hi.png" alt="Like Thumb" style="width:16px;height:16px;">
        <% end %>
        <a href="<%=contribution.url %>"> <%= contribution.title %> </a>
          <%='('%><%=link_to contribution.url, contribution.url%><%=')'%>
        </div>
        <div class="subtitle">
          <td><%= contribution.get_upvotes.size %> <%= ' points, by user ' %></td>
          <td> <%= link_to contribution.getUserName , contribution.user %> </td>
          <td><%= distance_of_time_in_words_to_now(contribution.created_at) %></td>
          <td><%= ' ago ' %></td>
          <td><%= '| ' %><%= link_to contribution.comments.count, contribution %> <%= link_to ' comments',contribution %></td>
          <!--<b><td><%= link_to 'Comments', contribution %></td></b>-->
          <% if(contribution.getUserId == session[:user_id]) %>
              <b><td><%= link_to 'Edit', edit_contribution_path(contribution) %></td></b>
              <b><td><%= link_to 'Destroy', contribution, method: :delete, data: { confirm: 'Are you sure?' } %></td></b>
            <% end %>
        </div>
      </li>
    <% end %>
  <% end %>
</ol> 

app/views/contributions/new.html.erb
<p/>
<div class="pageHeader">
 <b><%= link_to "Software 33 - Hacker News"  , contributions_path %></b> | 
 <font color="white"> Submit </font> 
    <div class="user_session">
        <% if current_user %>
            Signed in as <%= link_to current_user.username, current_user %> |
            <%= link_to 'Logout', "/delete_session" %>  &nbsp;
            <div class=image2><img src= <%= current_user.profile_image %> alt="Profile Image" style="width:20px;height:20px;"></div>
        <% end %>
        <% if !current_user  %>
            <%= link_to "Sign in with Twitter", "/auth/twitter" %>
        <% end %>
    </div>
</div>

<ol class=pageBody><%= render 'form' %>
</ol>  
    

app/views/contributions/show.html.erb
<p id="notice"><%= notice %></p>

 <% session[:threads_id] = session[:user_id] %>
<div class="pageHeader">
 <b><%= link_to "Software 33 - Hacker News"  , contributions_path %> </b>   
    <%= link_to 'new', contributions_path %> | 
    <%= link_to 'comments',comments_path %> | 
     <% if current_user %>
        <%= link_to 'threads', "/thread/" + String(current_user.id) %> | 
     <%end%>
    <%= link_to 'ask', "/ask" %> | 
    <%= link_to 'submit', new_contribution_path %> 
    <div class="user_session">
        <% if current_user %>
            Signed in as <%= link_to current_user.username, current_user %> |
            <%= link_to 'Logout', "/delete_session" %>  &nbsp;
            <div class=image2><img src= <%= current_user.profile_image %> alt="Profile Image" style="width:20px;height:20px;"></div>
        <% end %>
        <% if !current_user  %>
            <%= link_to "Sign in with Twitter", "/auth/twitter" %>
        <% end %>
    </div>
</div>

<ol class=pageBody>
<!--Contribution Info -->  
    <div class=titol>
      <%= @contribution.title %>
      <% if(current_user && !(current_user.liked? @contribution)) %>
        <td> | <b><%=link_to(image_tag('like.png'), {:controller => 'contributions', :action => 'upvote', :id => @contribution.id}, {:method => :put, :remote => true}) %></b></td>
         <% end %> 
          <% if(current_user && (current_user.liked? @contribution)) %>
            <img src="http://www.clker.com/cliparts/P/S/9/I/l/S/234-ed-s-sd-hi.png" alt="Like Thumb" style="width:16px;height:16px;">
          <% end %>
      <%= '| ' %> 
      <%= link_to 'Edit', edit_contribution_path(@contribution) %>
      <br>
    </div>
    
    <div class=subtitle>
      <td><%=@contribution.get_upvotes.size%></td>
      <td>points by: <%= link_to @contribution.getUserName , @contribution.user %> </td>
      <td><%= distance_of_time_in_words_to_now(@contribution.created_at) %></td>
      <td><%= ' ago ' %></td>
      <td><%= @contribution.comments.count %> comments</td>
      
    </div>
    
    <div class=textPreguntaOUrl>

      <% if @contribution.isAsk %>
        <%= @contribution.text %>
      <% end %>
      <% if @contribution.isURL %>
        <%= @contribution.url %>
      <% end %>
      <% if !@contribution.isURL && !@contribution.isAsk  %>
      <td>No es ni url ni pregunta </td>
      <% end %>
    </div>

<!--Add Comment -->  
    <p>
    <%= form_for(Comment.new) do |f| %>
        <% if session[:comment] %>
          <%= f.text_area :body, required: true, :value => session[:body] %>
          <% session[:comment] = false %>
        <% else %>
          <%= f.text_area :body, required: true %>
        <% end %>
        <%= f.hidden_field :contribution_id, :value => @contribution.id %>
        <%= f.hidden_field :user_id, :value => session[:user_id] %>
        <br> <%= f.submit 'Add comment' %> </br>
    <% end %>
    </p>

<!--Comments & Replies -->    
    <% if @contribution.comments != nil %>
          <!-- For each Comment  --> 
    <%    @contribution.comments.each do |comment| %>
      <li>
        <div class="subtitle">
          <td><%= distance_of_time_in_words_to_now(comment.created_at) %></td>
          <td><%= ' ago ' %></td>
          <td><%= ' by user ' %> <%= link_to comment.getUserName , comment.getUserName %> </td>
          <td> points: <%= comment.get_upvotes.size%>  </td>
          <td><%= '| ' %><%= comment.replies.count %> replies | </td>
          
          <% if(current_user && !(current_user.liked? comment)) %>
            <td> <b><%=link_to(image_tag('like.png'), {:controller => 'comments', :action => 'upvote', :id => comment.id}, {:method => :put, :remote => true}) %></b></td>
            <% end %> 
          <% if(current_user && (current_user.liked? comment)) %>
            <img src="http://www.clker.com/cliparts/P/S/9/I/l/S/234-ed-s-sd-hi.png" alt="Like Thumb" style="width:16px;height:16px;">
          <% end %>
          
        <% if(comment.getUserId == session[:user_id]) %>
          <b><td> | <%= link_to 'Destroy', comment, method: :delete %></td></b>
        <% end %>
        </div>
        <div class="CommentBody">
          <%= comment.body %>
        </div>
        </div class="CommentInfo">
          <b><td><%= link_to 'Reply', new_reply_path(:test => comment) %></td></b>
        </div>
        <!--Comment Replies --> 
        <ol class="repliesList">
          <% if comment.replies != nil %>
          <%    comment.replies.each do |reply| %>
          <li>
            <div class="subtitle">
              <td><%= distance_of_time_in_words_to_now(reply.created_at) %></td>
              <td><%= ' ago ' %></td>
              <td><%= 'by user ' %> <%= link_to reply.getUserName , reply.getUserName %> <%= '| ' %></td>
              <td> points: <%= reply.get_upvotes.size%>  </td>
              <% if(current_user && !(current_user.liked? reply)) %>
                <td> | <b><%=link_to(image_tag('like.png'), {:controller => 'replies', :action => 'upvote', :id => reply.id}, {:method => :put, :remote => true}) %></b></td>
                <% end %> 
              <% if(current_user && (current_user.liked? reply)) %>
                <img src="http://www.clker.com/cliparts/P/S/9/I/l/S/234-ed-s-sd-hi.png" alt="Like Thumb" style="width:16px;height:16px;">
              <% end %>
              <% if(reply.user.id == session[:user_id]) %>
              <b><td> | <%= link_to 'Destroy', reply, method: :delete %></td></b>
              <% end %>
            </div>
            <div class="Reply">
            <%= reply.body %>
            </div>
          </li>
          <%   end %>
          <% end %>
        </ol> 
        <br>
      </li>
    <%   end %>
  <% end %>

app/views/contributions/thread.html.erb
<p id="notice"><%= notice %></p>

<div class="pageHeader">
 <b><%= link_to "Software 33 - Hacker News"  , contributions_path %> </b>   
    <%= link_to 'new', contributions_path %> | 
    <%= link_to 'comments',comments_path %> | 
     <% if current_user %>
        <%= link_to 'threads', "/thread/" + String(current_user.id), {:style=>'color:white;', :class => "css_class"}  %> | 
     <%end%>
    <%= link_to 'ask', "/ask" %> | 
    <%= link_to 'submit', new_contribution_path %> 
    <div class="user_session">
        <% if current_user %>
            Signed in as <%= link_to current_user.username, current_user %> |
            <%= link_to 'Logout', "/delete_session" %>  &nbsp;
            <div class=image2><img src= <%= current_user.profile_image %> alt="Profile Image" style="width:20px;height:20px;"></div>
        <% end %>
        <% if !current_user  %>
            <%= link_to "Sign in with Twitter", "/auth/twitter" %>
        <% end %>
    </div>
</div>

<ol class="pageBody">
  <% params %>
  <% @contributions.reverse_each do |contribution| %>

    <% if contribution.getUserId == session[:threads_id] %>
    <li class="list">
      <% if contribution.isAsk %>
        <div class="ContributionTitle">
          <%= link_to contribution.title, contribution %>
        </div>
      <% end %>  
      <% if contribution.isURL %>
        <div class="ContributionTitle">
          <a href="<%=contribution.url %>"> <%= contribution.title %> </a>
          <%='('%><%=link_to contribution.url, contribution.url%><%=')'%>
        </div>
      <% end %>
      <div class="subtitle">
        <td><%= contribution.puntuacio %> <%= ' points, by user ' %></td>
        <td> <%= link_to contribution.getUserName , contribution.user %></td>
        <td><%= distance_of_time_in_words_to_now(contribution.created_at) %></td>
          <td><%= ' ago ' %></td>
          <td><%= '| ' %><%= link_to contribution.comments.count, contribution %> <%= link_to ' comments',contribution %></td>
        <!--<b><td><%= link_to 'Comments', contribution %></td></b>-->
        <% if(contribution.getUserId == session[:user_id]) %>
          <b><td><%= link_to 'Edit', edit_contribution_path(contribution) %></td></b>
          <b><td><%= link_to 'Destroy', contribution, method: :delete, data: { confirm: 'Are you sure?' } %></td></b>
         <% end %>
      </div>
    </li>
    <% end %>
  <% end %>
</ol> 